### ISSUE TITLE
Add troop name and credit (version + author)

### ISSUE THREAD

**Issue by Dreadaxe** [HENNIROCKS/warcry-card-creator#18]
Possibility to add or not.
For example like this
![image](https://user-images.githubusercontent.com/13752505/101768693-2e621100-3ae6-11eb-9461-7d0598cf4c6f.png)

**Comment by HENNIROCKS** [comment]
Won't add, just use the [template](https://hennirocks.github.io/warcry-card-creator/downloads.html) and be creative. Although this requires some skill in Adobe Photoshop or Affinity Photo:

1.) Create PNG:
![wcc__mask_darkoath-chieftess](https://user-images.githubusercontent.com/43246523/105744455-6f4ea180-5f3d-11eb-94da-9c2dde9545fc.png)

2.) Use PNG and add x-offset, e.g. -590
![wcc_std_darkoath-chieftess](https://user-images.githubusercontent.com/43246523/105744466-74135580-5f3d-11eb-8487-2aeb9c5a7c62.png)
