### ISSUE TITLE
Roster page Layout

### ISSUE THREAD

**Issue by Dreadaxe** [HENNIROCKS/warcry-card-creator#19]
For example
A roster layout
A4 8 cards
![Image](https://www.bss503.co.uk/images/8tv-90x65-29008l.png)

or
A4 9 cards
![Image](https://i.imgur.com/vOpnW9d.png)

More easy to print more easy to create armylist/roster

**Comment by HENNIROCKS** [comment]
Nah, I'll leave that to each of one's own to organize by themselves.
