### ISSUE TITLE
Faction Runemark,  and Abilities' text and runemarks

### ISSUE THREAD

**Issue by Dair8** [HENNIROCKS/warcry-card-creator#21]
Hi, 

Could be nice if we could choose not to use any faction runemark, so we could create our own generic abilities.
Also, if we could chose the order of the runemarks in the abilities sections would be nice (that way we could always put the leader runemark first and then another one, for example).
Finally, add the posibility of using runemarks in the text abilities (ex: beast or gargantuam runemarks).

Thanks in advance

**Comment by HENNIROCKS** [comment]
It is able [now](https://github.com/HENNIROCKS/warcry-card-creator/commit/30616daf0cfabe7d73c19f15695a41bbc7df4e07) to not choose a faction runemark for abilities.

>Finally, add the posibility of using runemarks in the text abilities (ex: beast or gargantuam runemarks).

Too hefty, requires full text editor with additional font-face; see also #17
