### ISSUE TITLE
[Ongoing] Nicer runemarks

### ISSUE THREAD

**Issue by HENNIROCKS** [HENNIROCKS/warcry-card-creator#6]
Note to self: add nicer runemarks when available. The ones I couldn't find on Varanscribe have been vectorized pretty quick and dirty by myself.

**Comment by Akaoni** [comment]
This might be helpful:
https://waywalkerstudios.com/updated-runemarks-font/

**Comment by HENNIROCKS** [comment]
> This might be helpful:
> https://waywalkerstudios.com/updated-runemarks-font/

Thanks, but that set is far out of date compared to mine (here).

**Comment by HENNIROCKS** [comment]
Added better faction runemark for **Lumineth Realm-lords** and added alternate **Cities of Sigmar** faction runemark, both vectorized from screenshots via Warhammer Merchandise. Included in both black and white in https://github.com/HENNIROCKS/warcry-card-creator/tree/master/runemarks

**Comment by Dreadaxe** [comment]
Other ideas of nice icon
HeroQuest and fanmade HQ icons
http://www.heroscribe.org/icons.html

**Comment by HENNIROCKS** [comment]
Looking for Grand Alliance runemarks.

**Comment by Moskonet** [comment]
Hey there :)

I'm working on a project and I'm also desperately looking for Grand
Alliances runemarks as well as the different runemarks for the various
cities of Sigmar.
Here's what I 've done so far: Warcry Compendiums
<https://drive.google.com/drive/folders/1eg7DcCDF8BYIxcr-F5R15d65UIWZkgoh?usp=sharing>,
reference sheets for all 4 alliances (Chaos is still WIP).
If you happen to make those runemarks or get someone to do it, I'd love to
know about it! I tried making them myself, but the result was meh.

Stay safe!

**Comment by Dreadaxe** [comment]
Possibility to add the faction rune mark of his computer?
