### ISSUE TITLE
Add faction runemark watermarks

### ISSUE THREAD

**Issue by HENNIROCKS** [HENNIROCKS/warcry-card-creator#7]
Personally not my cup of tea but maybe add the option to also attach the selected faction runemark as some sort of a watermark to the background; as in the original cards.

**Comment by HENNIROCKS** [comment]
Added branch `watermark`.

**Comment by Dreadaxe** [comment]
Colour icons
https://www.reddit.com/r/WarCry/comments/kcus88/runemarks_now_in_colour/

**Comment by HENNIROCKS** [comment]
I'll leave this be and kinda attach this to #18
