### ISSUE TITLE
Weapon profile icons see through

### ISSUE THREAD

**Issue by weissm2040** [HENNIROCKS/warcry-card-creator#9]
The icons (other than the attack symbol) are see-through on the card rather than the pure black on the official cards.

**Comment by HENNIROCKS** [comment]
Hello @weissm2040 and thanks for the feedback, I really appreciate it. What you're adressing is a conscious design decision by myself and nothing I intend to change in this repository. I find the current weapon statblock image far more interesting, graphically speaking. Especially when it may come to custom card backgrounds in the future :v:

**Comment by HENNIROCKS** [comment]
Overhought this and planning to make an option to switch between the current and a non-transparent weapon profile image.

**Comment by weissm2040** [comment]
To me it's inconsistent that the weapon statistics plus the weapon type symbol are all black, while the other icons on the weapon profile block are see through.

I think a neat approach might be to have the option for them (all) to be either transparent, or a colour of your choosing.

**Comment by HENNIROCKS** [comment]
Agreed. I added a black runemarks background image, it really looks more coherent. Might adjust the tone a little in the future, but basically sticking with that.

Adding options to this rather simple background image might even be a bit too much of a feature in general. Keeping it simple.
